### ISSUE TITLE
bot is not working on group chat 

### ISSUE THREAD

**Issue by Piyushdas1624** [ShinNouzen/Chitoge#14]
whenever i am adding my bot in some groups and using command like "/help" its not working . But when ever i am texting the bot privately its working fine and i have faced some glitch i thing whenever there is only my whattsapp account and my bot account on the group only (2) person on the group no one else added to the group  then the commands are working just fine

**Comment by LuckyYam** [comment]
Well... It's a problem from [Baileys](https://github.com/adiwajshing/Baileys). Please create an issue [here](https://github.com/adiwajshing/Baileys/issues) regarding this.

**Comment by Piyushdas1624** [comment]
> Well... It's a problem from [Baileys](https://github.com/adiwajshing/Baileys). Please create an issue [here](https://github.com/adiwajshing/Baileys/issues) regarding this.

ok I have issued it on baileys/issue
