### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Liton124** [ShinNouzen/Chitoge#18]
1.`add` command for adding members in groups by admins
2.`tic tac toe` game 
3. `Warn` command for doing any spam or giving inappropriate/suspicious link in group (for group members except admins)
4. `tts` command text to speech

**Comment by Oreki-san** [comment]
1. This command is already made but it can give the bot ban so I suggest to not use
2 and 3 aren't that necessary
4. 4.Good to implement 👍

**Comment by revanapriyandi** [comment]
add button
