### ISSUE TITLE
Request for new commands and bugs

### ISSUE THREAD

**Issue by ToniOfQ** [ShinNouzen/Chitoge#19]
Request
1 Google Image search
2 Pinterest Image search
3 Sticker search command

Bugs
nhentai is not working
anime and manga sometimes gives false info

**Comment by LuckyYam** [comment]
> Request 1 Google Image search 2 Pinterest Image search 3 Sticker search command
> 
> Bugs nhentai is not working anime and manga sometimes gives false info

What do you mean? Nhentai's not working? It's working perfectly for me. Did you specify the ID and the page of the doujin? For Anime and Manga I'll look into it.
