### ISSUE TITLE
Command improvement

### ISSUE THREAD

**Issue by Oreki-san** [ShinNouzen/Chitoge#22]
`wallpaper` command has very least resources like it can't search much anime characters , look into it

**Comment by LuckyYam** [comment]
Well.... I don't mind looking into it but the [module](https://www.npmjs.com/package/anime-wallpapers) itself is linked with [Wallpapercave](https://wallpapercave.com/), so I don't think it can have many sources.

**Comment by LuckyYam** [comment]
Check [this](https://github.com/ShineiIchijo/Chitoge/commit/9ebcfac79420d664a2891bde702bc80f085691eb) out.
