### ISSUE TITLE
HOW TO GET SESSION

### ISSUE THREAD

**Issue by sonzaiekkusu** [ShinNouzen/Chitoge#25]

**Comment by LuckyYam** [comment]
Well... it's your choice. Put anything you want there.

**Comment by sonzaiekkusu** [comment]
> Well... it's your choice. Put anything you want there.

Asena session?

**Comment by LuckyYam** [comment]
> > Well... it's your choice. Put anything you want there.
> 
> Asena session?

no

**Comment by LuckyYam** [comment]
It's just like password

**Comment by LuckyYam** [comment]
Put anything you want there.
Example: chitoge

**Comment by LuckyYam** [comment]
Please read the [guides](https://github.com/ShineiIchijo/Chitoge-Guides/blob/main/Heroku-Deploy-Guide.md). If you still have some problems, please feel free to re-open this issue. For now I'm closing it.
