### ISSUE TITLE
Heroku Deploy's Issue !!

### ISSUE THREAD

**Issue by ghost** [ShinNouzen/Chitoge#29]

**Comment by LuckyYam** [comment]
Hello! @jxdop, sorry for being late. To solve this problem, please fork this repository and deploy from there. Please feel free to re-open this issue if you're having any problem. For now I'm closing it.

**Comment by ghost** [comment]
Thnx it deployed perfectly ,but  now showing that free time quota has been exhausted...  What to do now ?

**Comment by LuckyYam** [comment]
> Thnx it deployed perfectly ,but now showing that free time quota has been exhausted... What to do now ?

It means that your free dynos have been exhausted. Create a new Heroku account and run your bot there.

**Comment by ghost** [comment]
Thanx,Now i stuck here , qr is not generated. 🙂!

**Comment by LuckyYam** [comment]
> Thanx,Now i stuck here , qr is not generated. 🙂!

Please make sure your mongodb uri ip has access from anywhere

**Comment by roshitha3321** [comment]
how do i get the QR ??
