### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by AliAryanTech** [ShinNouzen/Chitoge#32]
I deployed this repo few days ago and it was working, but now when I again deploy it 
It's not working.... I mean I can't login my app with WhatsApp Account and when I try again and again.... I mean refreshing page,  then soon the app got crushed. 

I think it's because of the recent update of the repo. If not, then please deploy it and check your repo. 
Thank you ShineiIchijo for creating this ❤️

**Comment by LuckyYam** [comment]
Can u please elaborate?

**Comment by AliAryanTech** [comment]
Whenever I try to scan QR Code
It shows me logging then (Nothing) Means, I scan the QR Code but it doesn't work.
Also If I use my old session password, then it shows me (No QR Generate) Something like this..... 

The problem is with app login with WhatsApp.

**Comment by AliAryanTech** [comment]
> Can u please elaborate?

The app is not logging with WhatsApp Account

**Comment by LuckyYam** [comment]
Please make sure you are not in Multi-Device beta

**Comment by AliAryanTech** [comment]
> Please make sure you are not in Multi-Device beta

Yes, I'm not using Multi-Device Beta

**Comment by AliAryanTech** [comment]
Can you fix. WhatsApp Login??
Whenever, I scan QR code it just shows me logging then nothing....

**Comment by LuckyYam** [comment]
Please dm [me](https://wa.me/+917005014836)
