### ISSUE TITLE
Error on scanning QR

### ISSUE THREAD

**Issue by rizuruu** [ShinNouzen/Chitoge#34]
Hi. I receive this error in logs on scanning QR

`TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined`

**Comment by LuckyYam** [comment]
You are probably using Multi-Device WhatsApp.
