### ISSUE TITLE
Messagehandler.ts issues 

### ISSUE THREAD

**Issue by ghost** [ShinNouzen/Chitoge#39]
Bro i am having an issue can you help me please 
![Screenshot_2022-03-21-20-10-55-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96679851/159285238-367a3777-7afd-4123-8cfd-72b9bed82f39.jpg)
 You can contact me on "https://wa.me//+918130784851" please help sir

**Comment by LuckyYam** [comment]
It's because you are having an empty command file
