### ISSUE TITLE
Need Help!! 

### ISSUE THREAD

**Issue by AliAryanTech** [ShinNouzen/Chitoge#40]
How to make a command available for admins and mods??
I don't know the syntax 🥲
I tried a lot but facing errors.... Can you tell me?

adminOnly: true || modsOnly: true,

**Comment by LuckyYam** [comment]
```TypeScript
export interface ICommand {
	client?: WAClient;
	handler?: MessageHandler;
	run(
		M: ISimplifiedMessage,
		parsedArgs: IParsedArgs
	): Promise<void | never> | void | never;
	config: {
		adminOnly?: boolean;
		aliases?: string[];
		description?: string;
		command: string;
		id?: string;
		category?: TCategory;
		usage?: string;
		dm?: boolean;
		baseXp?: number;
		modsOnly?: boolean;
	};
}
```
You can check it [here](https://github.com/ShineiIchijo/Chitoge/blob/main/src/typings/command.d.ts#L4)

**Comment by AliAryanTech** [comment]
> 

![Screenshot_20220324-233107](https://user-images.githubusercontent.com/85696485/159986270-1a658eb9-4553-4882-8ae6-079e7dcab14a.jpg)
Just tell me how to make this command available for admins and mods both!!
Like if there's a admin but it's not mod then he can use it also if there's a mod but not group admin he can also use that command

**Comment by LuckyYam** [comment]
> > 
> 
> ![Screenshot_20220324-233107](https://user-images.githubusercontent.com/85696485/159986270-1a658eb9-4553-4882-8ae6-079e7dcab14a.jpg) Just tell me how to make this command available for admins and mods both!! Like if there's a admin but it's not mod then he can use it also if there's a mod but not group admin he can also use that command

Unfortunately there isn't a config for that. But you can one like this - 

```TypeScript
if (!this.client.config.mods.includes(M.sender.jid) && !M.sender.isAdmin) 
      return void M.reply("You can't use this command")
```
I hope this clears your issue

**Comment by AliAryanTech** [comment]
> > > 
> > 
> > 
> > ![Screenshot_20220324-233107](https://user-images.githubusercontent.com/85696485/159986270-1a658eb9-4553-4882-8ae6-079e7dcab14a.jpg) Just tell me how to make this command available for admins and mods both!! Like if there's a admin but it's not mod then he can use it also if there's a mod but not group admin he can also use that command
> 
> Unfortunately there isn't a config for that. But you can one like this -
> 
> ```ts
> if (!this.client.config.mods.includes(M.sender.jid) && !M.sender.isAdmin) 
>       return void M.reply("You can't use this command")
> ```
> 
> I hope this clears your issue

You didn't tell me where I need to paste it
So, it's possible I do a mistake

**Comment by LuckyYam** [comment]
I think [this](https://www.freecodecamp.org/news/full-javascript-course-for-beginners/) is what you're looking for

**Comment by AliAryanTech** [comment]
> I think [this](https://www.freecodecamp.org/news/full-javascript-course-for-beginners/) is what you're looking for

Haha 🙄
Nice, Joke!! 

Now tell me where I put that code in [This](https://github.com/ShineiIchijo/Chitoge/blob/97b9e29dc4989f3083ad996f038706bafa91b8a2/src/commands/Moderation/Everyone.ts#L18) Command
