### ISSUE TITLE
error scan

### ISSUE THREAD

**Issue by techwiz37** [ShinNouzen/Chitoge#41]
i'am run yarn start and scan error
ode:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined

**Comment by techwiz37** [comment]
i'am join md

**Comment by LuckyYam** [comment]
@amiruldev20 I'm sorry but this WhatsApp Bot doesn't supports MD
