### ISSUE TITLE
Qr

### ISSUE THREAD

**Issue by SakshamBhadoria** [ShinNouzen/Chitoge#9]
It's showing qr is not generated yet what should I do or how much time it'll take

**Comment by LuckyYam** [comment]
Please give your app caffeine [here](https://kaffeine.herokuapp.com/) by entering your app name of the bot. After that please change your session and restart dynos. If it didn't work please keep on changing your session and restarting dynos until it gives you qr. And after 5-6 trys it didn't work? Please feel free to reopen this issue. For now I'm closing it.
